"""Human-reviewed classifications for every discovered Chroma access path."""

from __future__ import annotations

from typing import Any

from backend.chroma_access_models import build_enforced_inventory, stable_access_id


_PROFILES: dict[str, dict[str, Any]] = {
    "http_client": {
        "runtime": "production",
        "client_type": "http",
        "lifecycle": "read",
        "access_mode": "read_only",
        "may_create_collection": False,
        "may_mutate_records": False,
        "storage_internal_mutation_risk": "none",
        "current_owner": "github_vector_http_bridge",
        "migration_target": "central_http_client",
        "later_work_item": "central_http_client",
        "current_state": "accepted_existing_http_bridge",
        "migration_action": "adapt_to_central_factory_later",
        "notes": "Accepted narrow HTTP bridge construction remains unchanged and default-off upstream.",
    },
    "http_collection": {
        "runtime": "production",
        "client_type": "http",
        "lifecycle": "read",
        "access_mode": "read_only",
        "may_create_collection": False,
        "may_mutate_records": False,
        "storage_internal_mutation_risk": "server_owned",
        "current_owner": "github_vector_http_bridge",
        "migration_target": "registered_server_collection",
        "later_work_item": "collection_registry",
        "current_state": "accepted_existing_http_bridge",
        "migration_action": "adapt_to_central_factory_later",
        "notes": "Accepted bridge resolves the existing collection without creating it.",
    },
    "http_read": {
        "runtime": "production",
        "client_type": "http",
        "lifecycle": "read",
        "access_mode": "read_only",
        "may_create_collection": False,
        "may_mutate_records": False,
        "storage_internal_mutation_risk": "server_owned",
        "current_owner": "github_vector_http_bridge",
        "migration_target": "central_http_client",
        "later_work_item": "read_vector_migration",
        "current_state": "accepted_existing_http_bridge",
        "migration_action": "adapt_to_central_factory_later",
        "notes": "Accepted HTTP metadata read requests neither documents nor embeddings.",
    },
    "http_vector": {
        "runtime": "production",
        "client_type": "http",
        "lifecycle": "vector_query",
        "access_mode": "read_only",
        "may_create_collection": False,
        "may_mutate_records": False,
        "storage_internal_mutation_risk": "server_owned",
        "current_owner": "github_vector_http_bridge",
        "migration_target": "central_http_client",
        "later_work_item": "read_vector_migration",
        "current_state": "accepted_existing_http_bridge",
        "migration_action": "adapt_to_central_factory_later",
        "notes": "Accepted bounded vector query keeps server storage ownership outside this process.",
    },
    "central_http_client": {
        "runtime": "production",
        "client_type": "http",
        "lifecycle": "read",
        "access_mode": "read_only",
        "may_create_collection": False,
        "may_mutate_records": False,
        "storage_internal_mutation_risk": "none",
        "current_owner": "bounded_chroma_http_transport",
        "migration_target": "central_http_client",
        "later_work_item": "central_http_client",
        "current_state": "accepted_bounded_http_transport",
        "migration_action": "adopt_via_consumer_migration_later",
        "notes": "Authoritative lazy public httpx client construction with explicit no-retry bounded timeouts.",
    },
    "central_http_request": {
        "runtime": "production",
        "client_type": "http",
        "lifecycle": "index",
        "access_mode": "read_write",
        "may_create_collection": False,
        "may_mutate_records": True,
        "storage_internal_mutation_risk": "server_owned",
        "current_owner": "bounded_chroma_http_transport",
        "migration_target": "central_http_client",
        "later_work_item": "write_index_migration",
        "current_state": "accepted_bounded_http_transport",
        "migration_action": "preserve_bounded_semantic_operations",
        "notes": "One bounded no-retry HTTP request boundary serves allowlisted read and mutation operations.",
    },
    "central_http_collection": {
        "runtime": "production",
        "client_type": "http",
        "lifecycle": "read",
        "access_mode": "read_only",
        "may_create_collection": False,
        "may_mutate_records": False,
        "storage_internal_mutation_risk": "server_owned",
        "current_owner": "central_http_client_factory",
        "migration_target": "registered_server_collection",
        "later_work_item": "central_http_client",
        "current_state": "accepted_central_http_factory",
        "migration_action": "adopt_via_consumer_migration_later",
        "notes": "Existing-only lookup receives names resolved from validated registry semantic IDs.",
    },
    "chroma_server_lifecycle_health": {
        "runtime": "maintenance_only",
        "client_type": "http",
        "lifecycle": "maintenance",
        "access_mode": "read_only",
        "may_create_collection": False,
        "may_mutate_records": False,
        "storage_internal_mutation_risk": "server_owned",
        "current_owner": "chroma_server_lifecycle",
        "migration_target": "central_http_client",
        "later_work_item": "server_lifecycle",
        "current_state": "accepted_server_lifecycle",
        "migration_action": "preserve_explicit_lifecycle",
        "notes": "Explicit bounded heartbeat verifies readiness without collection access or application startup coupling.",
    },
    "operational_http_health": {
        "runtime": "production",
        "client_type": "http",
        "lifecycle": "read",
        "access_mode": "read_only",
        "may_create_collection": False,
        "may_mutate_records": False,
        "storage_internal_mutation_risk": "server_owned",
        "current_owner": "chroma_operational_reader",
        "migration_target": "central_http_client",
        "later_work_item": "status_read_migration",
        "current_state": "migrated_operational_http_read",
        "migration_action": "preserve_http_operational_read",
        "notes": "Bounded heartbeat gates safe count and inventory reads through the central HTTP factory.",
    },
    "fake_http_client": {
        "runtime": "test_only",
        "client_type": "fake_http",
        "lifecycle": "test_only",
        "access_mode": "read_only",
        "may_create_collection": False,
        "may_mutate_records": False,
        "storage_internal_mutation_risk": "none",
        "current_owner": "github_vector_test_seam",
        "migration_target": "central_http_client_test_double",
        "later_work_item": "test_infrastructure",
        "current_state": "accepted_test_seam",
        "migration_action": "preserve_test_injection",
        "notes": "Injected factory is used by isolated fake HTTP tests and never owns real storage.",
    },
    "ephemeral_fixture": {
        "runtime": "test_only",
        "client_type": "ephemeral_embedded",
        "lifecycle": "test_only",
        "access_mode": "read_write",
        "may_create_collection": True,
        "may_mutate_records": True,
        "storage_internal_mutation_risk": "local_process",
        "current_owner": "synthetic_sqlite_fixture",
        "migration_target": "isolated_test_storage",
        "later_work_item": "test_infrastructure",
        "current_state": "accepted_temporary_fixture",
        "migration_action": "preserve_temporary_isolation",
        "notes": "Temporary fixture creates github_evidence and optional profile_facts schema records.",
    },
    "ephemeral_persistent_client": {
        "runtime": "test_only",
        "client_type": "persistent_embedded",
        "lifecycle": "test_only",
        "access_mode": "read_write",
        "may_create_collection": False,
        "may_mutate_records": False,
        "storage_internal_mutation_risk": "local_process",
        "current_owner": "chroma_persistence_test_probe",
        "migration_target": "isolated_test_storage",
        "later_work_item": "test_infrastructure",
        "current_state": "accepted_temporary_fixture",
        "migration_action": "preserve_guarded_test_isolation",
        "notes": "Guarded subprocess constructor opens only verified-stopped temporary test persistence.",
    },
    "ephemeral_persistent_read": {
        "runtime": "test_only",
        "client_type": "persistent_embedded",
        "lifecycle": "test_only",
        "access_mode": "read_only",
        "may_create_collection": False,
        "may_mutate_records": False,
        "storage_internal_mutation_risk": "local_process",
        "current_owner": "chroma_persistence_test_probe",
        "migration_target": "isolated_test_storage",
        "later_work_item": "test_infrastructure",
        "current_state": "accepted_temporary_fixture",
        "migration_action": "preserve_guarded_test_isolation",
        "notes": "Disposable restored-copy parity reads run only after test-owned embedded access is authorized.",
    },
    "ephemeral_http_client_probe": {
        "runtime": "test_only",
        "client_type": "http",
        "lifecycle": "test_only",
        "access_mode": "read_only",
        "may_create_collection": False,
        "may_mutate_records": False,
        "storage_internal_mutation_risk": "none",
        "current_owner": "chroma_http_timeout_probe",
        "migration_target": "bounded_http_transport_adapter",
        "later_work_item": "test_infrastructure",
        "current_state": "accepted_ephemeral_http_probe",
        "migration_action": "retain_only_as_isolated_runtime_evidence",
        "notes": "Direct public HttpClient construction targets only a controlled delayed loopback endpoint.",
    },
    "ephemeral_http_admin": {
        "runtime": "test_only",
        "client_type": "http",
        "lifecycle": "test_only",
        "access_mode": "read_write",
        "may_create_collection": True,
        "may_mutate_records": True,
        "storage_internal_mutation_risk": "server_owned",
        "current_owner": "ephemeral_http_test_fixture",
        "migration_target": "isolated_ephemeral_http_server",
        "later_work_item": "test_infrastructure",
        "current_state": "accepted_ephemeral_http_fixture",
        "migration_action": "preserve_explicit_test_admin_boundary",
        "notes": "Explicit test-only preparation creates and seeds registered collections in temporary server storage.",
    },
    "ephemeral_http_read": {
        "runtime": "test_only",
        "client_type": "http",
        "lifecycle": "test_only",
        "access_mode": "read_only",
        "may_create_collection": False,
        "may_mutate_records": False,
        "storage_internal_mutation_risk": "server_owned",
        "current_owner": "ephemeral_http_test_fixture",
        "migration_target": "isolated_ephemeral_http_server",
        "later_work_item": "test_infrastructure",
        "current_state": "accepted_ephemeral_http_fixture",
        "migration_action": "preserve_validated_test_read",
        "notes": "Synthetic metadata read runs only after a central-factory lifecycle gate succeeds.",
    },
    "ephemeral_http_vector": {
        "runtime": "test_only",
        "client_type": "http",
        "lifecycle": "test_only",
        "access_mode": "read_only",
        "may_create_collection": False,
        "may_mutate_records": False,
        "storage_internal_mutation_risk": "server_owned",
        "current_owner": "ephemeral_http_test_fixture",
        "migration_target": "isolated_ephemeral_http_server",
        "later_work_item": "test_infrastructure",
        "current_state": "accepted_ephemeral_http_fixture",
        "migration_action": "preserve_validated_test_vector_query",
        "notes": "Synthetic vector query runs only after a central-factory lifecycle gate succeeds.",
    },
}


def _record(
    module: str,
    symbol: str,
    line: int,
    semantic_role: str,
    operation: str,
    collection: str,
    collection_resolution: str,
    profile: str,
) -> dict[str, Any]:
    record = {
        "module": module,
        "symbol": symbol,
        "line": line,
        "semantic_role": semantic_role,
        "operation": operation,
        "collection": collection,
        "collection_resolution": collection_resolution,
        **_PROFILES[profile],
    }
    record["access_id"] = stable_access_id(record)
    return record


_A = "backend/chroma_http_transport.py"
_F = "backend/chroma_http_client_factory.py"
_L = "backend/chroma_server_lifecycle.py"
_O = "backend/chroma_operational_reader.py"
_E = "tests/chroma_http_test_support.py"
_P = "tests/chroma_persistence_test_support.py"

REVIEWED_ACCESS_RECORDS = [
    _record(_A, "_default_httpx_client_builder", 319, "low_level_http_client", "client construction", "not_applicable", "literal", "central_http_client"),
    _record(_A, "BoundedChromaHttpTransport._request_json", 765, "request", "http request", "not_applicable", "literal", "central_http_request"),
    _record(_F, "ChromaHttpClientFactory.get_collection_handle", 626, "get_collection", "get collection", "dynamic_collection", "dynamic", "central_http_collection"),
    _record(_L, "_bounded_heartbeat", 319, "heartbeat", "heartbeat", "not_applicable", "literal", "chroma_server_lifecycle_health"),
    _record(_O, "ChromaOperationalReader.read_collection_status", 234, "heartbeat", "heartbeat", "not_applicable", "literal", "operational_http_health"),
    _record(_E, "_probe_chroma_readiness", 353, "independent_http_request", "http request", "not_applicable", "literal", "ephemeral_http_read"),
    _record(_E, "_create_registered_collection_for_test", 586, "create_collection", "create collection", "dynamic_collection", "dynamic", "ephemeral_http_admin"),
    _record(_E, "_create_registered_collection_for_test", 595, "add", "add", "dynamic_collection", "dynamic", "ephemeral_http_admin"),
    _record(_E, "read_collection_for_test", 600, "get", "get", "dynamic_collection", "dynamic", "ephemeral_http_read"),
    _record(_E, "query_collection_for_test", 608, "query", "query", "dynamic_collection", "dynamic", "ephemeral_http_vector"),
    _record(_E, "_construct_public_chroma_test_client", 642, "direct_chromadb_http_client", "client construction", "not_applicable", "literal", "ephemeral_http_client_probe"),
    _record(_P, "create_test_owned_persistent_client", 71, "default_persistent_client", "client construction", "not_applicable", "literal", "ephemeral_persistent_client"),
    _record(_P, "read_test_owned_collection_snapshot", 101, "get_collection", "get collection", "dynamic_collection", "dynamic", "ephemeral_persistent_read"),
    _record(_P, "read_test_owned_collection_snapshot", 102, "count", "count", "dynamic_collection", "dynamic", "ephemeral_persistent_read"),
    _record(_P, "read_test_owned_collection_snapshot", 103, "get", "get", "dynamic_collection", "dynamic", "ephemeral_persistent_read"),
    _record(_P, "read_test_owned_collection_snapshot", 107, "query", "query", "dynamic_collection", "dynamic", "ephemeral_persistent_read"),
]

INVENTORY = build_enforced_inventory(REVIEWED_ACCESS_RECORDS)
EXPECTED_INVENTORY_DIGEST = "932d10a011195960583c44c273abe96e0c199736b74604270012af079ad13e68"

if EXPECTED_INVENTORY_DIGEST and INVENTORY["inventory_digest"] != EXPECTED_INVENTORY_DIGEST:
    raise RuntimeError("reviewed_inventory_digest_mismatch")
